### PR TITLE
Docker improvements

### PR DESCRIPTION
**Pull request by mjs**
* Configure PostgreSQL in docker image instead of in the docker entry
  point. There no reason to delay this until container startup.
* Simplify stopping of the container
* Expose PostgreSQL server port from container. This is useful for
  development and confirming DB contents from the
  outside. PostgreSQL's port is exposed at 5400 to avoid collisions
  with a PostgreSQL server on the host.
* Avoid the need for the container pid file Given that a static container name is used, the pid file is unnecessary.
* Move minio startup to docker-entrypoint. This makes more sense given
  that setting up Minio doesn't depend on the cacophony-api
  code. This also speeds things up somewhat.

### CODE REVIEW

**Comment by ben-biddington** [comment]
Make it so!

**Comment by mjs** [comment]
@ben-biddington thanks for the review. Can you please submit a review with an approval? The PR can't be merged without a positive review.

**Comment by ben-biddington** [comment]
Sure -- how?

**Comment by mjs** [comment]
@ben-biddington thanks!

**Pull request merged**
